name: Rust

on:
  push:
    branches: [ "develop" ]
    tags:
      - 'v*.*.*'

  pull_request:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: AddTarget
      run: | 
        rustup target add x86_64-unknown-linux-musl
        rustup target add x86_64-pc-windows-msvc
        rustup target add x86_64-apple-darwin
    - name: Build
      run: |
        cargo build --release --verbose --target x86_64-unknown-linux-musl
        cargo build --release --verbose --target x86_64-pc-windows-msvc
        cargo build --release --verbose --target x86_64-apple-darwin
    - name: Package
      shell: bash
      run: |
          cp target/x86_64-unknown-linux-musl/release/custm-dns-server .
          cp target/x86_64-pc-windows-msvc/release/custm-dns-server.exe .
          cp target/x86_64-apple-darwin/release/custm-dns-server .
    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
          files: 'custm-dns-server*'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
