name: Rust

on:
  push:
    branches: [ "develop" ]
    tags:
      - 'v*.*.*'

  pull_request:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Build target
      run: cargo build --release --verbose
    - name: Package
      shell: bash
      run: |
          cd target/release
          ls
          tar czvf ../../custom-dns-server-${{ matrix.os }}.tar.gz custom-dns-server ../../config.json
          cd -
    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
          files: 'custom-dns-server*'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
